services:
  gremlin-server:
    image: tinkerpop/gremlin-server:3.6.2
    container_name: gremlin-server
    ports:
      - "8183:8182"
    volumes:
      - ./scripts:/opt/gremlin-server/scripts
    environment:
      - GREMLIN_SERVER_HOST=0.0.0.0
      - GREMLIN_SERVER_PORT=8182
      - JANUSGRAPH_HOST=janusgraph
      - JANUSGRAPH_PORT=8182
    networks:
      - janusnet
    depends_on:
      - janusgraph

networks:
  janusnet:
    external: true
