services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    volumes:
      - ./janusgraph-config:/etc/opt/janusgraph
      - ./janusgraph-config/log4j-server.properties:/opt/janusgraph/conf/log4j-server.properties
      - ./logs/janusgraph-logs:/opt/janusgraph/logs
    environment:
      - JANUS_PROPS_TEMPLATE=inmemory
      - JANUSGRAPH_LOG_LEVEL=DEBUG
      
    ports:
      - "8182:8182"
    networks:
      - janusnet
    command: >
      sh -c "tail -f  /opt/janusgraph/logs/janusgraph.log"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true

  gremlin-server:
    image: tinkerpop/gremlin-server:3.6.2
    container_name: gremlin-server
    ports:
      - "8183:8182"
    volumes:
      - ./scripts:/opt/gremlin-server/scripts
    environment:
      - GREMLIN_SERVER_HOST=0.0.0.0
      - GREMLIN_SERVER_PORT=8182
    networks:
      - janusnet
    depends_on:
      - janusgraph
    tty: true
    stdin_open: true

networks:
  janusnet:
    driver: bridge