

services:
  neo4j1:
    image: neo4j:latest
    container_name: neo4j1
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: neo4j/verysecretpassword
    healthcheck:
      test: cypher-shell -u neo4j -p verysecretpassword "SHOW DATABASES"
      interval: 10s
      timeout: 5s
      retries: 5



  app1:
    build: 
      context: .
      dockerfile: GRACEDockerfile
    container_name: GRACE1
    ports:
      - "3000:3000"
    environment:
      WS_URI: "ws://wsserver:1234"
      NEO4J_URI: "bolt://neo4j1:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "verysecretpassword"
    depends_on:
      neo4j1:
        condition: service_healthy

