services:
  neo4j1:
    image: neo4j:latest
    container_name: neo4j1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/verysecretpassword
    healthcheck:
      test: [ "CMD", "bash", "-c", "cypher-shell -u neo4j -p verysecretpassword 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10

  app1:
    build:
      context: ..
      dockerfile: ./Dockerfiles/GRACEDockerfile
    container_name: GRACE1
    ports:
      - "3000:3000"
    environment:
      WS_URI: "ws://wsserver:1234"
      NEO4J_URI: "bolt://neo4j1:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "verysecretpassword"
    depends_on:
      neo4j1:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "5000:3000"
    depends_on:
      - prometheus