host: 0.0.0.0
port: 8182
channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer

graphs: {
  graph: conf/janusgraph-inmemory.properties
}

scriptEngines: {
  gremlin-groovy: {
    plugins: {
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {
        files: [scripts/empty-sample.groovy]
      }
    }
  }
}

serializers:
  - {className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3 }

metrics: {
  consoleReporter: {enabled: false},
  csvReporter: {enabled: false},
  jmxReporter: {enabled: false},
  slf4jReporter: {enabled: true}
}

strictTransactionManagement: false
